
export const sidebarMenu = [
  {
    url: '#/InformationManagement',
    key: '#/InformationManagement',
    defaultImgUrl: require('../styles/images/sidebarMenu/icon_zixun.png'),
    selectedImgUrl: require('../styles/images/sidebarMenu/icon_zixun.png'),
    title: '资讯管理',
    unClickable: true,
    subMenu: [
      {
        url: '#/InformationManagement/Article',
        key: '#/InformationManagement/Article',
        title: '文章管理',
        power: '20001.21601.000',
        subBreadcrumb: [{
          url: '#/InformationManagement/Article/add',
          key: '#/InformationManagement/Article/add',
          title: '新建文章',
          unClickable: true,
        }, {
          url: '#/InformationManagement/Article/EditArticle',
          key: '#/InformationManagement/Article/EditArticle',
          title: '编辑文章',
          unClickable: true,
        }, {
          url: '#/InformationManagement/Article/DetailArticle',
          key: '#/InformationManagement/Article/DetailArticle',
          title: '文章详情',
          unClickable: true,
        },
        {
          url: '#/InformationManagement/Article/SpecialNews',
          key: '#/InformationManagement/Article/SpecialNews',
          title: '专题栏目列表',
          unClickable: true,
        },
        {
          url: '#/InformationManagement/Article/NewsActivityList',
          key: '#/InformationManagement/Article/NewsActivityList',
          title: '栏目资讯活动列表',
          unClickable: true,
        }, {
          url: '#/InformationManagement/Article/PageView',
          key: '#/InformationManagement/Article/PageView',
          title: '浏览数',
          unClickable: true,
        }, {
          url: '#/InformationManagement/Article/ZanView',
          key: '#/InformationManagement/Article/ZanView',
        }, {
          url: '#/InformationManagement/Article/PageVote',
          key: '#/InformationManagement/Article/PageVote',
          title: '点赞数',
          unClickable: true,
        }, {
          url: '#/InformationManagement/Article/PageComment',
          key: '#/InformationManagement/Article/PageComment',
          title: '评论数',
          unClickable: true,
        }, {
          url: '#/InformationManagement/Information/CommentDetail',
          key: '#/InformationManagement/Information/CommentDetail',
          title: '评论详情',
          unClickable: true,
        }],
      }, {
        url: '#/InformationManagement/Video',
        key: '#/InformationManagement/Video',
        title: '视频管理',
        power: '20001.21602.000',
        subBreadcrumb: [{
          url: '#/InformationManagement/Video/NewVideo',
          key: '#/InformationManagement/Video/NewVideo',
          title: '新建视频',
          unClickable: true,
        }, {
          url: '#/InformationManagement/Video/EditVideo',
          key: '#/InformationManagement/Video/EditVideo',
          title: '编辑视频',
          unClickable: true,
        }, {
          url: '#/InformationManagement/Video/DetailVideo',
          key: '#/InformationManagement/Video/DetailVideo',
          title: '视频详情',
          unClickable: true,
        }, {
          url: '#/InformationManagement/Video/PageView',
          key: '#/InformationManagement/Video/PageView',
          title: '浏览数',
          unClickable: true,
        }, {
          url: '#/InformationManagement/Video/PageComment',
          key: '#/InformationManagement/Video/PageComment',
          title: '评论数',
          unClickable: true,
        }, {
          url: '#/InformationManagement/Video/CommentDetail',
          key: '#/InformationManagement/Video/CommentDetail',
          title: '评论详情',
          unClickable: true,
        }],
      },
      {
        url: '#/InformationManagement/Magazine',
        key: '#/InformationManagement/Magazine',
        title: '杂志管理',
        defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
        selectedImgUrl: require('../styles/images/sidebarMenu/icon_jianhao.png'),
        unClickable: true,
        subMenu: [
          {
            url: '#/InformationManagement/Magazine/List',
            key: '#/InformationManagement/Magazine/List',
            title: '杂志列表',
            power: '20001.21605.000',
            subBreadcrumb: [{
              url: '#/InformationManagement/Magazine/Add',
              key: '#/InformationManagement/Magazine/Add',
              title: '新建杂志',
              unClickable: true,
            }, {
              url: '#/InformationManagement/Magazine/Edit',
              key: '#/InformationManagement/Magazine/Edit',
              title: '编辑杂志',
              unClickable: true,
            }, {
              url: '#/InformationManagement/Magazine/Comments',
              key: '#/InformationManagement/Magazine/Comments',
            }, {
              url: '#/InformationManagement/Magazine/PageComment',
              key: '#/InformationManagement/Magazine/PageComment',
              title: '评论数',
              unClickable: true,
            },
            {
              url: '#/InformationManagement/Magazine/PageView',
              key: '#/InformationManagement/Magazine/PageView',
              title: '浏览数',
              unClickable: true,
            },
            ],
          },
          {
            url: '#/InformationManagement/Magazine/Magazines',
            key: '#/InformationManagement/Magazine/Magazines',
            title: '杂志系列管理',
            power: '20001.21606.000',
          },
        ],
      },
      {
        url: '#/InformationManagement/project',
        key: '#/InformationManagement/project',
        title: '专题管理',
        defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
        selectedImgUrl: require('../styles/images/sidebarMenu/icon_jianhao.png'),
        unClickable: true,
        subMenu: [{
          url: '#/InformationManagement/project/list',
          key: '#/InformationManagement/project/list',
          title: '普通专题',
          power: '20001.21608.000',
          subBreadcrumb: [{
            url: '#/InformationManagement/project/Add',
            key: '#/InformationManagement/project/Add',
            title: '新建专题',
            unClickable: true,
          }, {
            url: '#/InformationManagement/project/Edit',
            key: '#/InformationManagement/project/Edit',
            title: '编辑专题',
            unClickable: true,
          }, {
            url: '#/InformationManagement/project/normaltopic',
            key: '#/InformationManagement/project/normaltopic',
            title: '专题栏目',
            unClickable: true,
          }, {
            url: '#/InformationManagement/project/normalcontentmanagement',
            key: '#/InformationManagement/project/normalcontentmanagement',
            title: '专题栏目内容管理',
            unClickable: true,
          }, {
            url: '#/InformationManagement/project/ViewLists',
            key: '#/InformationManagement/project/ViewLists',
          }, {
            url: '#/InformationManagement/General/PageView',
            key: '#/InformationManagement/General/PageView',
            title: '浏览数',
            unClickable: true,
          }, {
            url: '#/InformationManagement/General/PageComment',
            key: '#/InformationManagement/General/PageComment',
            title: '评论数',
            unClickable: true,
          },
          ],
        }, {
          url: '#/InformationManagement/project/Bank',
          key: '#/InformationManagement/project/Bank',
          title: '部门专题',
          power: '20001.21607.000',
          subBreadcrumb: [
            {
              url: '#/InformationManagement/Project/PageView',
              key: '#/InformationManagement/Project/PageView',
              title: '浏览数',
              unClickable: true,
            }, {
              url: '#/InformationManagement/Project/PageComment',
              key: '#/InformationManagement/Project/PageComment',
              title: '评论数',
              unClickable: true,
            }, {//新增部门评论详情页xwx2018/12/12
              url: '#/InformationManagement/project/CommentDetail',
              key: '#/InformationManagement/project/CommentDetail',
              title: '评论详情',
              unClickable: true,
            }, {
              url: '#/InformationManagement/project/topic',
              key: '#/InformationManagement/project/topic',
              title: '专题栏目',
              unClickable: true,
            }, {
              url: '#/InformationManagement/project/contentmanagement',
              key: '#/InformationManagement/project/contentmanagement',
              title: '专题栏目内容管理',
              unClickable: true,
            }, {
              url: '#/InformationManagement/project/addG',
              key: '#/InformationManagement/project/addG',
              title: '新建部门专题',
              unClickable: true,
            }, {
              url: '#/InformationManagement/project/editor',
              key: '#/InformationManagement/project/editor',
              title: '编辑部门专题',
              unClickable: true,
            }],
        }],
      },
    ],

  },
  {
    url: '#/EventManagement',
    title: '活动管理',
    key: '#/EventManagement',
    defaultImgUrl: require('../styles/images/sidebarMenu/icon_huodongguanli.png'),
    selectedImgUrl: require('../styles/images/sidebarMenu/icon_huodongguanli.png'),
    unClickable: true,
    subMenu: [
      {
        url: '#/EventManagement/Apply',
        key: '#/EventManagement/Apply',
        title: '报名活动',
        defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
        selectedImgUrl: require('../styles/images/sidebarMenu/icon_jianhao.png'),
        subMenu: [
          {
            url: '#/EventManagement/Apply/List',
            key: '#/EventManagement/Apply/List',
            title: '报名活动列表',
            power: '20002.22001.000',
            subBreadcrumb: [{
              url: '#/EventManagement/Apply/Add',
              key: '#/EventManagement/Apply/Add',
              title: '新建报名活动',
              unClickable: true,
            }, {
              url: '#/EventManagement/Apply/Edit',
              key: '#/EventManagement/Apply/Edit',
              title: '编辑报名活动',
              unClickable: true,
            },
            {
              url: '#/EventManagement/Apply/Detail',
              key: '#/EventManagement/Apply/Detail',
              title: '报名活动详情',
              unClickable: true,
            },
            {
              url: '#/EventManagement/Apply/ApplyFields',
              key: '#/EventManagement/Apply/ApplyFields',
              title: '设置报名表单',
              unClickable: true,
            },
            {
              url: '#/EventManagement/Apply/ApplyInfo',
              key: '#/EventManagement/Apply/ApplyInfo',
              title: '查看报名信息',
              unClickable: true,
            },
            {                                 //20181106   浏览  参与   点赞   评论
              url: '#/EventManagement/Apply/JoinList',
              key: '#/EventManagement/Apply/JoinList',
              title: '参与人数详情',
              unClickable: true,
            },
            {
              url: '#/EventManagement/Apply/ViewList',
              key: '#/EventManagement/Apply/ViewList',
              title: '浏览人数详情',
              unClickable: true,
            },
            {
              url: '#/EventManagement/Apply/LikesList',
              key: '#/EventManagement/Apply/LikesList',
              title: '点赞数详情',
              unClickable: true,
            },
            {
              url: '#/EventManagement/Apply/CommentList',
              key: '#/EventManagement/Apply/CommentList',
              title: '评论数详情',
              unClickable: true,
            }, {
              url: '#/EventManagement/Apply/CommentDetail',
              key: '#/EventManagement/Apply/CommentDetail',
              title: '评论详情',
              unClickable: true,
            },
            ],
          }, {
            url: '#/EventManagement/Apply/Field',
            key: '#/EventManagement/Apply/Field',
            title: '报名字段管理',
            power: '20002.22002.000',
            subBreadcrumb: [{
              url: '#/EventManagement/Apply/FieldAdd',
              key: '#/EventManagement/Apply/FieldAdd',
              title: '新建报名字段',
              unClickable: true,
            }, {
              url: '#/EventManagement/Apply/FieldEdit',
              key: '#/EventManagement/Apply/FieldEdit',
              title: '编辑报名字段',
              unClickable: true,
            }],
          },
        ],


      }, {
        url: '#/EventManagement/Examination',
        key: '#/EventManagement/Examination',
        title: '考试活动',
        defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
        selectedImgUrl: require('../styles/images/sidebarMenu/icon_jianhao.png'),
        unClickable: true,
        subMenu: [{
          url: '#/EventManagement/Examination/List',
          key: '#/EventManagement/Examination/List',
          title: '考试活动列表',
          power: '20002.22003.000',
          subBreadcrumb: [{
            url: '#/EventManagement/Examination/Add',
            key: '#/EventManagement/Examination/Add',
            title: '新建考试活动',
            unClickable: true,
          }, {
            url: '#/EventManagement/Examination/Edit',
            key: '#/EventManagement/Examination/Edit',
            title: '编辑考试活动',
            unClickable: true,
          }, {
            url: '#/EventManagement/Examination/Detail',
            key: '#/EventManagement/Examination/Detail',
            title: '考试活动详情',
            unClickable: true,
          }, {                                 //20181106   浏览  参与   点赞   评论
            url: '#/EventManagement/Examination/JoinList',
            key: '#/EventManagement/Examination/JoinList',
            title: '参与人数详情',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Examination/ViewList',
            key: '#/EventManagement/Examination/ViewList',
            title: '浏览人数详情',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Examination/LikesList',
            key: '#/EventManagement/Examination/LikesList',
            title: '点赞数详情',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Examination/CommentList',
            key: '#/EventManagement/Examination/CommentList',
            title: '评论数详情',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Examination/CommentDetail',
            key: '#/EventManagement/Examination/CommentDetail',
            title: '评论内容详情',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Examination/QuestionsSettings',
            key: '#/EventManagement/Examination/QuestionsSettings',
            title: '设置考试题目',
            unClickable: true,
            subBreadcrumb: [{
              url: '#/EventManagement/Examination/AddCustomQuestion',
              key: '#/EventManagement/Examination/AddCustomQuestion',
              title: '添加题目',
              unClickable: true,
            }, {
              url: '#/EventManagement/Examination/EditCustomQuestion',
              key: '#/EventManagement/Examination/EditCustomQuestion',
              title: '编辑题目',
              unClickable: true,
            }],
          }, {
            url: '#/EventManagement/Examination/Score',
            key: '#/EventManagement/Examination/Score',
            title: '查看考试成绩',
            unClickable: true,
          }, {
            url: '#/EventManagement/Examination/StatisticalResults',
            key: '#/EventManagement/Examination/StatisticalResults',
            title: '查看统计结果',
            unClickable: true,
          },
          ],
        }, {
          url: '#/EventManagement/Examination/Bank',
          key: '#/EventManagement/Examination/Bank',
          title: '考试题库管理',
          power: '20002.22009.000',
          subBreadcrumb: [{
            url: '#/EventManagement/Examination/QuestionsManagement',
            key: '#/EventManagement/Examination/QuestionsManagement',
            title: '题目管理',
            unClickable: true,
            subBreadcrumb: [{
              url: '#/EventManagement/Examination/AddQuestionsConfiguration',
              key: '#/EventManagement/Examination/AddQuestionsConfiguration',
              title: '新建题目',
              unClickable: true,
            }, {
              url: '#/EventManagement/Examination/EditQuestionsConfiguration',
              key: '#/EventManagement/Examination/EditQuestionsConfiguration',
              title: '编辑题目',
              unClickable: true,
            }],
          }],
        },
        // {
        //   url: '#/EventManagement/Examination/CustomQuestionsManagement',
        //   key: '#/EventManagement/Examination/CustomQuestionsManagement',
        //   title: '考试题目管理',
        //   power: '20002.22004.000',
        //   subBreadcrumb: [{
        //     url: '#/EventManagement/Examination/QuestionsManagement',
        //     key: '#/EventManagement/Examination/QuestionsManagement',
        //     title: '题目管理',
        //     unClickable: true,
        //     subBreadcrumb: [{
        //       url: '#/EventManagement/Examination/AddCustomQuestionsManagement',
        //       key: '#/EventManagement/Examination/AddCustomQuestionsManagement',
        //       title: '新建题目',
        //       unClickable: true,
        //     }, {
        //       url: '#/EventManagement/Examination/EditCustomQuestionsManagement',
        //       key: '#/EventManagement/Examination/EditCustomQuestionsManagement',
        //       title: '编辑题目',
        //       unClickable: true,
        //     }],
        //   }],
        // },
        {
          url: '#/EventManagement/Examination/CustomQuestionsManagement',
          key: '#/EventManagement/Examination/CustomQuestionsManagement',
          title: '考试题目管理',
          power: '20002.22004.000',
          subBreadcrumb: [{
            url: '#/EventManagement/Examination/AddCustomQuestionsManagement',
            key: '#/EventManagement/Examination/AddCustomQuestionsManagement',
            title: '新建题目',
            unClickable: true,
          }, {
            url: '#/EventManagement/Examination/EditCustomQuestionsManagement',
            key: '#/EventManagement/Examination/EditCustomQuestionsManagement',
            title: '编辑题目',
            unClickable: true,
          }],
        },

        ],
      }, {
        url: '#/EventManagement/Questionnaire',
        key: '#/EventManagement/Questionnaire',
        title: '问卷活动',
        defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
        selectedImgUrl: require('../styles/images/sidebarMenu/icon_jianhao.png'),
        subMenu: [{
          url: '#/EventManagement/Questionnaire/List',
          key: '#/EventManagement/Questionnaire/List',
          title: '问卷活动列表',
          power: '20002.22005.000',
          subBreadcrumb: [{
            url: '#/EventManagement/Questionnaire/Add',
            key: '#/EventManagement/Questionnaire/Add',
            title: '新建问卷活动',
            unClickable: true,
          }, {
            url: '#/EventManagement/Questionnaire/Edit',
            key: '#/EventManagement/Questionnaire/Edit',
            title: '编辑问卷活动',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Questionnaire/Detail',
            key: '#/EventManagement/Questionnaire/Detail',
            title: '问卷活动详情',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Questionnaire/QuestionnaireInfo',
            key: '#/EventManagement/Questionnaire/QuestionnaireInfo',
            title: '查看问卷结果',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Questionnaire/StatisticalResults',
            key: '#/EventManagement/Questionnaire/StatisticalResults',
            title: '查看统计结果',
            unClickable: true,
          },
          {                                 //20181106   浏览  参与   点赞   评论
            url: '#/EventManagement/Questionnaire/JoinList',
            key: '#/EventManagement/Questionnaire/JoinList',
            title: '参与人数详情',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Questionnaire/ViewList',
            key: '#/EventManagement/Questionnaire/ViewList',
            title: '浏览人数详情',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Questionnaire/LikesList',
            key: '#/EventManagement/Questionnaire/LikesList',
            title: '点赞数详情',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Questionnaire/CommentList',
            key: '#/EventManagement/Questionnaire/CommentList',
            title: '评论数详情',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Questionnaire/CommentDetail',
            key: '#/EventManagement/Questionnaire/CommentDetail',
            title: '评论内容详情',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Questionnaire/TopicList',
            key: '#/EventManagement/Questionnaire/TopicList',
            title: '设置问卷题目',
            unClickable: true,
            subBreadcrumb: [{
              url: '#/EventManagement/Questionnaire/TopicAdd',
              key: '#/EventManagement/Questionnaire/TopicAdd',
              title: '自定义问卷题目',
              unClickable: true,
            }, {
              url: '#/EventManagement/Questionnaire/TopicEdit',
              key: '#/EventManagement/Questionnaire/TopicEdit',
              title: '编辑问卷题目',
              unClickable: true,
            }],
          }],
        }, {
          url: '#/EventManagement/Questionnaire/TopicManagement',
          key: '#/EventManagement/Questionnaire/TopicManagement',
          title: '问卷题目管理',
          power: '20002.22006.000',
          subBreadcrumb: [{
            url: '#/EventManagement/Questionnaire/TopicManagementEdit',
            key: '#/EventManagement/Questionnaire/TopicManagementEdit',
            title: '编辑问卷题目',
            unClickable: true,
          }, {
            url: '#/EventManagement/Questionnaire/TopicManagementAdd',
            key: '#/EventManagement/Questionnaire/TopicManagementAdd',
            title: '新建问卷题目',
            unClickable: true,
          }],
        }],

      }, {
        url: '#/EventManagement/Vote',
        key: '#/EventManagement/Vote',
        title: '投票活动',
        defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
        selectedImgUrl: require('../styles/images/sidebarMenu/icon_jianhao.png'),
        subMenu: [{
          url: '#/EventManagement/Vote/List',
          key: '#/EventManagement/Vote/List',
          title: '投票活动列表',
          power: '20002.22007.000',
          subBreadcrumb: [{
            url: '#/EventManagement/Vote/Add',
            key: '#/EventManagement/Vote/Add',
            title: '新建投票活动',
            unClickable: true,
          }, {
            url: '#/EventManagement/Vote/Edit',
            key: '#/EventManagement/Vote/Edit',
            title: '编辑投票活动',
            unClickable: true,
          }, {
            url: '#/EventManagement/Vote/Detail',
            key: '#/EventManagement/Vote/Detail',
            title: '投票活动详情',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Vote/VoteInfo',
            key: '#/EventManagement/Vote/VoteInfo',
            title: '查看投票结果',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Vote/StatisticalResults',
            key: '#/EventManagement/Vote/StatisticalResults',
            title: '查看统计结果',
            unClickable: true,
          },
          {                                 //20181106   浏览  参与   点赞   评论
            url: '#/EventManagement/Vote/JoinList',
            key: '#/EventManagement/Vote/JoinList',
            title: '参与人数详情',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Vote/ViewList',
            key: '#/EventManagement/Vote/ViewList',
            title: '浏览人数详情',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Vote/LikesList',
            key: '#/EventManagement/Vote/LikesList',
            title: '点赞数详情',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Vote/CommentList',
            key: '#/EventManagement/Vote/CommentList',
            title: '评论数详情',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Vote/CommentDetail',
            key: '#/EventManagement/Vote/CommentDetail',
            title: '评论内容详情',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Vote/TopicList',
            key: '#/EventManagement/Vote/TopicList',
            title: '设置投票题目',
            unClickable: true,
            subBreadcrumb: [{
              url: '#/EventManagement/Vote/TopicAdd',
              key: '#/EventManagement/Vote/TopicAdd',
              title: '新建投票题目',
              unClickable: true,
            }, {
              url: '#/EventManagement/Vote/TopicEdit',
              key: '#/EventManagement/Vote/TopicEdit',
              title: '编辑投票题目',
              unClickable: true,
            }],
          }],
        }, {
          url: '#/EventManagement/Vote/TopicMangement',
          key: '#/EventManagement/Vote/TopicMangement',
          title: '投票题目管理',
          power: '20002.22008.000',
          subBreadcrumb: [{
            url: '#/EventManagement/Vote/TopicMangementAdd',
            key: '#/EventManagement/Vote/TopicMangementAdd',
            title: '新建投票题目',
            unClickable: true,
          }, {
            url: '#/EventManagement/Vote/TopicMangementEdit',
            key: '#/EventManagement/Vote/TopicMangementEdit',
            title: '编辑投票题目',
            unClickable: true,
          }],
        }],
      },
      {
        url: '#/EventManagement/Order',
        key: '#/EventManagement/Order',
        title: '订购活动',
        defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
        selectedImgUrl: require('../styles/images/sidebarMenu/icon_jianhao.png'),
        unClickable: true,
        subMenu: [{
          url: '#/EventManagement/Order/List',
          key: '#/EventManagement/Order/List',
          title: '订购活动列表',
          power: '20002.22010.000',
          subBreadcrumb: [{
            url: '#/EventManagement/Order/Add',
            key: '#/EventManagement/Order/Add',
            title: '新建订购活动',
            unClickable: true,
          }, {
            url: '#/EventManagement/Order/Edit',
            key: '#/EventManagement/Order/Edit',
            title: '编辑订购活动',
            unClickable: true,
          }, {
            url: '#/EventManagement/Order/Detail',
            key: '#/EventManagement/Order/Detail',
            title: '订购活动详情',
            unClickable: true,
          }, {
            url: '#/EventManagement/Order/SetShopping',
            key: '#/EventManagement/Order/SetShopping',
            title: '设置订购商品',
            unClickable: true,
          }, {
            url: '#/EventManagement/Order/OrderInformation',
            key: '#/EventManagement/Order/OrderInformation',
            title: '查看订购信息',
            unClickable: true,
          }, {                                 //20181106   浏览  参与   点赞   评论
            url: '#/EventManagement/Order/JoinList',
            key: '#/EventManagement/Order/JoinList',
            title: '参与人数详情',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Order/ViewList',
            key: '#/EventManagement/Order/ViewList',
            title: '浏览人数详情',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Order/LikesList',
            key: '#/EventManagement/Order/LikesList',
            title: '点赞数详情',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Order/CommentList',
            key: '#/EventManagement/Order/CommentList',
            title: '评论数详情',
            unClickable: true,
          },
          {
            url: '#/EventManagement/Order/CommentDetail',
            key: '#/EventManagement/Order/CommentDetail',
            title: '评论内容详情',
            unClickable: true,
          },
          ],
        },
        {
          url: '#/EventManagement/Order/Merchant',
          key: '#/EventManagement/Order/Merchant',
          title: '商家管理',
          // power: '20002.22006.000',
          subBreadcrumb: [
            {
              url: '#/EventManagement/Order/MerchantProduct',
              key: '#/EventManagement/Order/MerchantProduct',
              title: '商品管理',
            },
            {
              url: '#/EventManagement/Order/AddProduct',
              key: '#/EventManagement/Order/AddProduct',
              title: '新建商品',
            },
            {
              url: '#/EventManagement/Order/EditProduct',
              key: '#/EventManagement/Order/EditProduct',
              title: '编辑商品',
            },
            {
              url: '#/EventManagement/Order/MerchantDetail',
              key: '#/EventManagement/Order/MerchantDetail',
              title: '订单详情',
            }
          ]
        },
        // {
        //   url: '#/EventManagement/Order/Commodity',
        //   key: '#/EventManagement/Order/Commodity',
        //   title: '商品管理',
        //   // power: '20002.22007.000',
        //   subBreadcrumb: [{
        //     url: '#/EventManagement/Order/CommodityEdit',
        //     key: '#/EventManagement/Order/CommodityEdit',
        //     title: '编辑',
        //     unClickable: true,
        //   },
        //   {
        //     url: '#/EventManagement/Order/CommodityAdd',
        //     key: '#/EventManagement/Order/CommodityAdd',
        //     title: '新建',
        //     unClickable: true,
        //   }],
        //   },
          {
            url: '#/EventManagement/Order/Classification',
            key: '#/EventManagement/Order/Classification',
            title: '分类列表',
            unClickable: true,
            subBreadcrumb: [
              {
                url: '#/EventManagement/Order/secondClassify',
                key: '#/EventManagement/Order/secondClassify',
                // url: '#/GoodsManagetion/secondClassify',
                // key: '#/GoodsManagetion/secondClassify',
                title: '二级分类',
                unClickable: true,
              }
            ]
            // power: '20002.22006.000',
          },
        ],
      },
      /*   {
            url: '#/EventManagement/Task',
            key: '#/EventManagement/Task',
            title: '任务活动',
            defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
            selectedImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
            unClickable: true,
            subMenu: [{
              url: '#/EventManagement/Task/List/Redirect',
              key: '#/EventManagement/Task/List/Redirect',
              title: '任务活动列表',
            }, {
              url: '#/EventManagement/Task/Theme',
              key: '#/EventManagement/Task/Theme',
              title: '任务主题管理',
            }, {
              url: '#/EventManagement/Task/Type',
              key: '#/EventManagement/Task/Type',
              title: '任务类型管理',
            }],
          }*/
    ],
  },
  {
    url: '#/PartyBuildGarden',
    key: '#/PartyBuildGarden',
    defaultImgUrl: require('../styles/images/sidebarMenu/icon_dangjian.png'),
    selectedImgUrl: require('../styles/images/sidebarMenu/icon_dangjian.png'),
    title: '党建园地',
    unClickable: true,
    subMenu: [
      {
        url: '#/PartyBuildGarden/PartyMembers',
        key: '#/PartyBuildGarden/PartyMembers',
        title: '党员管理',
        defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
        selectedImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
        power: '20005.23007.000',
        subBreadcrumb: [{
          url: '#/PartyBuildGarden/NewPartyMember',
          key: '#/PartyBuildGarden/NewPartyMember',
          title: '新建党员用户',
          unClickable: true,
        }, {
          url: '#/PartyBuildGarden/PartyFeeManagement',
          key: '#/PartyBuildGarden/PartyFeeManagement',
          title: '党费管理',
          unClickable: true,
        },
        {
          url: '#/PartyBuildGarden/NewEditPartyMember',
          key: '#/PartyBuildGarden/NewEditPartyMember',
          title: '编辑党员用户',
          unClickable: true,
        },
        ],
      },
      {
        url: '#/PartyBuildGarden/PartyApply',
        key: '#/PartyBuildGarden/PartyApply',
        title: '入党申请管理',
        power: '20005.23003.000',
      },
      {
        url: '#/PartyBuildGarden/PartyMenOut',
        key: '#/PartyBuildGarden/PartyMenOut',
        title: '转出党员',
        power: '20005.23007.000',
        subBreadcrumb: [{
          url: '#/PartyBuildGarden/PartyEdit',
          key: '#/PartyBuildGarden/PartyEdit',
          title: '编辑菜单',
          unClickable: true,
        }],
      },
      {
        url: '#/PartyBuildGarden/PartyOrganization',
        key: '#/PartyBuildGarden/PartyOrganization',
        title: '党组织管理',
        power: '20005.23002.000',
      },
      {
        url: '#/PartyBuildGarden/PartyLearning',
        key: '#/PartyBuildGarden/PartyLearning',
        title: '党建学习管理',
        power: '20005.23018.000',
        subBreadcrumb: [
          {
            url: '#/PartyBuildGarden/PartyLearning/AddLearn',
            key: '#/PartyBuildGarden/PartyLearning/AddLearn',
            title: '新建党建学习',
            unClickable: true,
          },
          {
            url: '#/PartyBuildGarden/PartyLearning/EditLearn',
            key: '#/PartyBuildGarden/PartyLearning/EditLearn',
            title: '编辑党建学习',
            unClickable: true,
          },
          {
            url: '#/PartyBuildGarden/PartyLearning/DetailLearn',
            key: '#/PartyBuildGarden/PartyLearning/DetailLearn',
            title: '党建学习详情',
            unClickable: true,
          },
          {
            url: '#/PartyBuildGarden/PartyLearning/Note',
            key: '#/PartyBuildGarden/PartyLearning/Note',
            title: '党建学习笔记',
            unClickable: true,
          },
          {
            url: '#/PartyBuildGarden/PartyLearning/CompletionRate',
            key: '#/PartyBuildGarden/PartyLearning/CompletionRate',
            title: '查看完成率',
            unClickable: true,
          },
        ],
      },
      {
        url: '#/PartyBuildGarden/PartyTask',
        key: '#/PartyBuildGarden/PartyTask',
        title: '党建任务管理',
        power: '20005.23006.000',
        subBreadcrumb: [
          {
            url: '#/PartyBuildGarden/PartyTask/Add',
            key: '#/PartyBuildGarden/PartyTask/Add',
            title: '新建党建任务',
            unClickable: true,
          },
          {
            url: '#/PartyBuildGarden/PartyTask/Edit',
            key: '#/PartyBuildGarden/PartyTask/Edit',
            title: '编辑党建任务',
            unClickable: true,
          },
          {
            url: '#/PartyBuildGarden/PartyTask/Detail',
            key: '#/PartyBuildGarden/PartyTask/Detail',
            title: '党建任务详情',
            unClickable: true,
          },
          {
            url: '#/PartyBuildGarden/PartyTask/CompletionRate',
            key: '#/PartyBuildGarden/PartyTask/CompletionRate',
            title: '查看完成率',
            unClickable: true,
          },
        ],
      },

      {
        url: '#/PartyBuildGarden/PublicAnnouncement',
        key: '#/PartyBuildGarden/PublicAnnouncement',
        title: '张榜公布管理',
        power: '20004.24003.003',
        subBreadcrumb: [
          {
            url: '#/PartyBuildGarden/PublicAnnouncement/PublicDetail',
            key: '#/PartyBuildGarden/PublicAnnouncement/DePublicDetailtail',
            title: '榜单详情',
            unClickable: true,
          },
        ],
      },
      {
        url: '#/PartyBuildGarden/Dictionary',
        key: '#/PartyBuildGarden/Dictionary',
        title: '字典管理',
        defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
        selectedImgUrl: require('../styles/images/sidebarMenu/icon_jianhao.png'),
        unClickable: true,
        subMenu: [
          {
            url: '#/PartyBuildGarden/Dictionary/TaskTopic',
            key: '#/PartyBuildGarden/Dictionary/TaskTopic',
            title: '任务主题管理',
            power: '20005.23008.000',
            subBreadcrumb: [{
              url: '#/PartyBuildGarden/Dictionary/TaskTopicAdd',
              key: '#/PartyBuildGarden/Dictionary/TaskTopicAdd',
              title: '新建任务主题',
              unClickable: true,
            }, {
              url: '#/PartyBuildGarden/Dictionary/TaskTopicEdit',
              key: '#/PartyBuildGarden/Dictionary/TaskTopicEdit',
              title: '编辑任务主题',
              unClickable: true,
            },
            ],
          },
          {
            url: '#/PartyBuildGarden/Dictionary/TaskType',
            key: '#/PartyBuildGarden/Dictionary/TaskType',
            title: '任务类型管理',
            power: '20005.23009.000',
            subBreadcrumb: [{
              url: '#/PartyBuildGarden/Dictionary/TaskTypeAdd',
              key: '#/PartyBuildGarden/Dictionary/TaskTypeAdd',
              title: '新建类型主题',
              unClickable: true,
            }, {
              url: '#/PartyBuildGarden/Dictionary/TaskTypeEdit',
              key: '#/PartyBuildGarden/Dictionary/TaskTypeEdit',
              title: '编辑任务类型',
              unClickable: true,
            },
            ],
          },
        ],
      },
    ],
  },

  {
    url: '#/TradeManager',
    key: '#/TradeManager',
    defaultImgUrl: require('../styles/images/sidebarMenu/icon_gonghuiguanli.png'),
    selectedImgUrl: require('../styles/images/sidebarMenu/icon_gonghuiguanli.png'),
    title: '工会管理',
    subMenu: [
      {
        url: '#/TradeManager/Organization',
        key: '#/TradeManager/Organization',
        title: '工会组织管理',
        power: '20007.21704.000',
      },
      {
        url: '#/TradeManager/Member',
        key: '#/TradeManager/Member',
        title: '会员管理',
        power: '20007.21705.000',
      },
      {
        url: '#/TradeManager/Suggestions',
        key: '#/TradeManager/Suggestions',
        title: '建言管理',
        power: '20030.20031.000',
      },
      {
        url: '#/TradeManager/LearnManagation/List',
        key: '#/TradeManager/LearnManagation/List',
        title: '学习管理',
        power: '20007.21712.000',
        subBreadcrumb: [{
          url: '#/TradeManager/LearnManagation/Add',
          key: '#/TradeManager/LearnManagation/Add',
          title: '新建学习',
        },
        {
          url: '#/TradeManager/LearnManagation/Edit',
          key: '#/TradeManager/LearnManagation/Edit',
          title: '编辑学习',
        },
        {
          url: '#/TradeManager/LearnManagation/Detail',
          key: '#/TradeManager/LearnManagation/Detail',
          title: '学习详情',
        },
        {
          url: '#/TradeManager/LearnManagation/Note',
          key: '#/TradeManager/LearnManagation/Note',
          title: '查看学习笔记',
        }
        ],
      },
      {
        url: '#/TradeManager/ChairmanBox',
        key: '#/TradeManager/ChairmanBox',
        defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
        selectedImgUrl: require('../styles/images/sidebarMenu/icon_jianhao.png'),
        title: '主席信箱',
        subMenu: [{
          url: '#/TradeManager/ChairmanBox/CommonBox',
          key: '#/TradeManager/ChairmanBox/CommonBox',
          title: '普通信件',
          power: '20007.21703.000',
          subBreadcrumb: [{
            url: '#/TradeManager/ChairmanBox/CommonBox/Detail',
            key: '#/TradeManager/ChairmanBox/CommonBox/Detail',
            title: '信件详情',
          }],
        }, {
          url: '#/TradeManager/ChairmanBox/ReportBox',
          key: '#/TradeManager/ChairmanBox/ReportBox',
          title: '上报信件',
          power: '20007.21707.000',
          subBreadcrumb: [{
            url: '#/TradeManager/ChairmanBox/ReportBox/Detail',
            key: '#/TradeManager/ChairmanBox/ReportBox/Detail',
            title: '信件详情',
          }],
        }],
      },
      {
        url: '#/TradeManager/DifficultyHelp',
        key: '#/TradeManager/DifficultyHelp',
        defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
        selectedImgUrl: require('../styles/images/sidebarMenu/icon_jianhao.png'),
        title: '困难帮扶',
        subMenu: [{
          url: '#/TradeManager/DifficultyHelp/CommonBox',
          key: '#/TradeManager/DifficultyHelp/CommonBox',
          title: '普通信件',
          power: '20007.21710.000',
          subBreadcrumb: [{
            url: '#/TradeManager/DifficultyHelp/CommonBox/Detail',
            key: '#/TradeManager/DifficultyHelp/CommonBox/Detail',
            title: '信件详情',
          }],
        }, {
          url: '#/TradeManager/DifficultyHelp/ReportBox',
          key: '#/TradeManager/DifficultyHelp/ReportBox',
          title: '上报信件',
          power: '20007.21711.000',
          subBreadcrumb: [{
            url: '#/TradeManager/DifficultyHelp/ReportBox/Detail',
            key: '#/TradeManager/DifficultyHelp/ReportBox/Detail',
            title: '信件详情',
          }],
        }],
      },
      {
        url: '#/TradeManager/PowerManagation',
        key: '#/TradeManager/PowerManagation',
        defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
        selectedImgUrl: require('../styles/images/sidebarMenu/icon_jianhao.png'),
        title: '维权管理',
        subMenu: [{
          url: '#/TradeManager/PowerManagation/CommonBox',
          key: '#/TradeManager/PowerManagation/CommonBox',
          title: '普通信件',
          power: '20007.21708.000',
          subBreadcrumb: [{
            url: '#/TradeManager/PowerManagation/CommonBox/Detail',
            key: '#/TradeManager/PowerManagation/CommonBox/Detail',
            title: '信件详情',
          }],
        }, {
          url: '#/TradeManager/PowerManagation/ReportBox',
          key: '#/TradeManager/PowerManagation/ReportBox',
          title: '上报信件',
          power: '20007.21709.000',
          subBreadcrumb: [{
            url: '#/TradeManager/PowerManagation/ReportBox/Detail',
            key: '#/TradeManager/PowerManagation/ReportBox/Detail',
            title: '信件详情',
          }],
        }],
      },
      {
        url: '#/TradeManager/ForumManagation',
        key: '#/TradeManager/ForumManagation',
        defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
        selectedImgUrl: require('../styles/images/sidebarMenu/icon_jianhao.png'),
        title: '论坛管理',
        subMenu: [{
          url: '#/TradeManager/ForumManagation/CardManagation',
          key: '#/TradeManager/ForumManagation/CardManagation',
          title: '帖子管理',
          power: '20007.21701.000',
          subBreadcrumb: [{
            url: '#/TradeManager/ForumManagation/CardManagation/Detail',
            key: '#/TradeManager/ForumManagation/CardManagation/Detail',
            title: '帖子详情',
          }],
        }, {
          url: '#/TradeManager/ForumManagation/CommentManagation',
          key: '#/TradeManager/ForumManagation/CommentManagation',
          title: '评论管理',
          power: '20007.21706.000',
          subBreadcrumb: [{
            url: '#/TradeManager/ForumManagation/CommentManagation/Detail',
            key: '#/TradeManager/ForumManagation/CommentManagation/Detail',
            title: '评论详情',
          }, {
            url: '#/TradeManager/ForumManagation/CommentManagation/SecondDetail',
            key: '#/TradeManager/ForumManagation/CommentManagation/SecondDetail',
            title: '详情',
          },
          ],
        }, {
          url: '#/TradeManager/ForumManagation/ThemeManagation',
          key: '#/TradeManager/ForumManagation/ThemeManagation',
          title: '主题管理',
          power: '20007.21702.000',
          subBreadcrumb: [{
            url: '#/TradeManager/ForumManagation/ThemeManagation/Add',
            key: '#/TradeManager/ForumManagation/ThemeManagation/Add',
            title: '新建主题',
          }, {
            url: '#/TradeManager/ForumManagation/ThemeManagation/Edit',
            key: '#/TradeManager/ForumManagation/ThemeManagation/Edit',
            title: '编辑主题',
          }],
        },
        ],
      },
    ],
  },

  // {
  //   url: '#/Statistics/',
  //   key: '#/Statistics/',
  //   defaultImgUrl: require('../styles/images/sidebarMenu/icon_baobiao.png'),
  //   selectedImgUrl: require('../styles/images/sidebarMenu/icon_baobiao.png'),
  //   title: '统计分析',
  //   subMenu: [
  //     {
  //       url: '#/Statistics/User',
  //       key: '#/Statistics/User',
  //       title: '用户分析',
  //       unClickable: true,
  //       defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
  //       selectedImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
  //       subMenu: [
  //         {
  //           url: '#/Statistics/User/Reg',
  //           key: '#/Statistics/User/Reg',
  //           title: '总注册人数',
  //         },
  //       ],
  //     },
  //     {
  //       url: '#/Statistics/Content',
  //       key: '#/Statistics/Content',
  //       title: '内容分析',
  //     },
  //     {
  //       url: '#/Statistics/Menu',
  //       key: '#/Statistics/Menu',
  //       title: '菜单分析',
  //     },
  //     {
  //       url: '#/Statistics/Message',
  //       key: '#/Statistics/Message',
  //       title: '消息分析',
  //     },
  //     {
  //       url: '#/Statistics/Score',
  //       key: '#/Statistics/Score',
  //       title: '积分分析',
  //     },
  //   ],
  // },


  {
    url: '#/PointManagement',
    title: '积分管理',
    key: '#/PointManagement',
    defaultImgUrl: require('../styles/images/sidebarMenu/icon_tongji1.png'),
    selectedImgUrl: require('../styles/images/sidebarMenu/icon_tongji1.png'),
    unClickable: true,
    subMenu: [{
      url: '#/PointManagement/UserPoint',
      key: '#/PointManagement/UserPoint',
      title: '用户积分管理',
      power: '20010.24001.000',
      unClickable: true,
      subBreadcrumb: [{
        url: '#/PointManagement/PointInfo',
        key: '#/PointManagement/PointInfo',
        title: '经验值变更详情',
        unClickable: true,
      }, {
        url: '#/PointManagement/TreasureInfo',
        key: '#/PointManagement/TreasureInfo',
        title: '普通积分变更详情',
        unClickable: true,
      }, {
        url: '#/PointManagement/PartyMemHonorInfo',
        key: '#/PointManagement/PartyMemHonorInfo',
        title: '党员荣誉积分变更详情',
        unClickable: true,
      }, {
        url: '#/PointManagement/BirthdayTicketInfo',
        key: '#/PointManagement/BirthdayTicketInfo',
        title: '生日券变更详情',
        unClickable: true,
      }, {
        url: '#/PointManagement/CinemaTicketInfo',
        key: '#/PointManagement/CinemaTicketInfo',
        title: '电影票积分变更详情',
        unClickable: true,
      }, {
        url: '#/PointManagement/FestivitiesMaterialInfo',
        key: '#/PointManagement/FestivitiesMaterialInfo',
        title: '过节物资积分变更详情',
        unClickable: true,
      }],
    }, {
      url: '#/PointManagement/SpecialPoint',
      key: '#/PointManagement/SpecialPoint',
      title: '专项积分发放管理',
      power: '20011.21602.000',
      unClickable: true,
      subBreadcrumb: [{
        url: '#/PointManagement/SpecialPoint/AddTask',
        key: '#/PointManagement/SpecialPoint/AddTask',
        title: '添加任务',
        unClickable: true,
      }, {
        url: '#/PointManagement/SpecialPoint/EditTask',
        key: '#/PointManagement/SpecialPoint/EditTask',
        title: '编辑任务',
        unClickable: true,
      }, {
        url: '#/PointManagement/CategoryManagement',
        key: '#/PointManagement/CategoryManagement',
        title: '类别管理',
        unClickable: true,
      }],
    }, {
      url: '#/PointManagement/RechargePoint',
      key: '#/PointManagement/RechargePoint',
      title: '积分充值配置',
      power: '20011.21603.000',
      unClickable: true,
    }, {
      url: '#/PointManagement/RechargeRecord',
      key: '#/PointManagement/RechargeRecord',
      title: '用户充值记录',
      power: '20011.21604.000',
      unClickable: true,
    },
    {//平台积分明细xwx2018/12/25
      url: '#/PointManagement/PlatformPoint',
      key: '#/PointManagement/PlatformPoint',
      title: '平台积分明细',
      defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
      selectedImgUrl: require('../styles/images/sidebarMenu/icon_jianhao.png'),
      unClickable: true,
      subMenu: [
        {
          url: '#/PointManagement/PlatformPoint/PartyMemberChange',
          key: '#/PointManagement/PlatformPoint/PartyMemberChange',
          title: '党员荣誉积分变更记录',
          power: '20011.21606.000',
        },
        {
          url: '#/PointManagement/PlatformPoint/BirthdayCouponChange',
          key: '#/PointManagement/PlatformPoint/BirthdayCouponChange',
          title: '生日券积分变更记录',
          power: '20011.21605.000',
        },
        {
          url: '#/PointManagement/PlatformPoint/MoviePiaoChange',
          key: '#/PointManagement/PlatformPoint/MoviePiaoChange',
          title: '电影票积分变更记录',
          power: '20011.21607.000',
        },
        {
          url: '#/PointManagement/PlatformPoint/FestivalMaterialsChange',
          key: '#/PointManagement/PlatformPoint/FestivalMaterialsChange',
          title: '过节物资积分变更记录',
          power: '20011.21609.000',
        },
        {
          url: '#/PointManagement/PlatformPoint/CurrencyIntegralChange',
          key: '#/PointManagement/PlatformPoint/CurrencyIntegralChange',
          title: '通用积分变更记录',
          power: '20011.21608.000',
        },
      ],
    },
    {//对账导出xwx2019/2/26
      url: '#/PointManagement/ReconciliationExport',
      key: '#/PointManagement/ReconciliationExport',
      title: '对账导出',
      power: '20011.21610.000',
      unClickable: true,
    },
    {
      url: '#/PointManagement/PointRule',
      key: '#/PointManagement/PointRule',
      title: '积分规则管理',
      power: '20010.24002.000',
      unClickable: true,
    },
    ],
  },

  // {
  //   url: '#/SystemSettings',
  //   title: '事项提醒',
  //   key: '#/MattersRemind',
  //   defaultImgUrl: require('../styles/images/sidebarMenu/icon_fold.png'),
  //   selectedImgUrl: require('../styles/images/sidebarMenu/icon_unfold.png'),
  //   subMenu: [{
  //     url: '#/SystemSettings/MattersRemind/Redirect',
  //     key: 'http://t.manage.iyouqu.com.cn/admin/remind/query.jhtml?youqums',
  //     title: '事项提醒管理',
  //     power: '20001.21032.000',
  //   }, {
  //     url: '#/SystemSettings/PartyBranchReminder/Redirect',
  //     key: 'http://t.manage.iyouqu.com.cn/admin/remind/queryRemindeInfo.jhtml?youqums',
  //     title: '党支部换届提醒管理',
  //     power: '20001.21033.000',
  //   }],
  // }, {
  //   url: '#/SystemSettings',
  //   title: '服务',
  //   key: '#/ShuttleManagement',
  //   defaultImgUrl: require('../styles/images/sidebarMenu/icon_fold.png'),
  //   selectedImgUrl: require('../styles/images/sidebarMenu/icon_unfold.png'),
  //   subMenu: [{
  //     url: '#/SystemSettings/ShuttleManagement/Redirect',
  //     key: 'http://t.manage.iyouqu.com.cn/admin/shuttle/query.jhtml?youqums',
  //     title: '班车管理',
  //     power: '20001.21024.000',
  //   }, {
  //     url: '#/SystemSettings/CommodityManagement/Redirect',
  //     key: 'http://t.manage.iyouqu.com.cn/admin/goods/query.jhtml?youqums',
  //     title: '商品管理',
  //     power: '20001.21025.000',
  //   }],
  // }, {
  //   url: '#/SystemSettings',
  //   title: '积分商城',
  //   key: '#/shopping',
  //   defaultImgUrl: require('../styles/images/sidebarMenu/icon_fold.png'),
  //   selectedImgUrl: require('../styles/images/sidebarMenu/icon_unfold.png'),
  //   subMenu: [{
  //     url: '#/SystemSettings/MallActivityManagement/Redirect',
  //     key: 'http://t.manage.iyouqu.com.cn/admin/activity/query.jhtml?searchMap[\'typeId\']=8&youqums',
  //     title: '商品活动管理',
  //     power: '20001.21026.000',
  //   }, {
  //     url: '#/SystemSettings/SpecialPointsManagement/Redirect',
  //     key: 'http://t.manage.iyouqu.com.cn/admin/specialPoint/query.jhtml?youqums',
  //     title: '专项积分管理',
  //     power: '20001.21027.000',
  //   }, {
  //     url: '#/SystemSettings/CreditGrantingUserManagement/Redirect',
  //     key: 'http://t.manage.iyouqu.com.cn/admin/specialPoint/queryMaintain.jhtml?youqums',
  //     title: '积分发放用户管理',
  //     power: '20001.21028.000',
  //   }, {
  //     url: '#/SystemSettings/IntegralRechargeConfiguration/Redirect',
  //     key: 'http://t.manage.iyouqu.com.cn/admin/pointCharge/query.jhtml?youqums',
  //     title: '积分充值配置',
  //     power: '20001.21029.000',
  //   }, {
  //     url: '#/SystemSettings/IntegralRechargeManagement/Redirect',
  //     key: 'http://t.manage.iyouqu.com.cn/admin/pointChargeInfo/query.jhtml?youqums',
  //     title: '积分充值管理',
  //     power: '20001.21030.000',
  //   }, {
  //     url: '#/SystemSettings/CheckExport/Redirect',
  //     key: 'http://t.manage.iyouqu.com.cn/admin/keBanShopLog/query.jhtml?youqums',
  //     title: '对账导出',
  //     power: '20001.21031.000',
  //   }],
  // },

  // 20181030
  {
    url: '#/Message',
    key: '#/Message',
    defaultImgUrl: require('../styles/images/sidebarMenu/icon_shixiangtixing.png'),
    selectedImgUrl: require('../styles/images/sidebarMenu/icon_shixiangtixing.png'),
    title: '消息管理',
    unClickable: true,
    subMenu: [
      {
        url: '#/Message/Notice',
        key: '#/Message/Notice',
        title: '通知管理',
        power: '20008.23002.000',
        // unClickable: true,
        subBreadcrumb: [{
          url: '#/Message/Notice/Edit',
          key: '#/Message/Notice/Edit',
          title: '添加通知',
          unClickable: true,
        }],
      },
      {
        url: '#/Message/Idea',
        key: '#/Message/Idea',
        title: '意见反馈',
        power: '20008.23001.000',
      },
      {
        url: '#/Message/Inform',
        key: '#/Message/Inform',
        title: '举报管理',
        power: '20008.23003.000',
      },
    ],
  },

  {
    url: '#/Service',
    key: '#/Service',
    defaultImgUrl: require('../styles/images/sidebarMenu/icon_fuwu1.png'),
    selectedImgUrl: require('../styles/images/sidebarMenu/icon_fuwu1.png'),
    title: '服务管理',
    // power: '20001.20888.000',
    unClickable: true,
    subMenu: [
      {
        url: '#/Service/BusList',
        key: '#/Service/BusList',
        title: '班车管理',
        power: '20888.22001.000',
        unClickable: true,
      },
      {
        url: '#/Service/CheckInList',
        key: '#/Service/CheckInList',
        title: '考勤管理',
        power: '20888.22004.000',
        unClickable: true,
      },
      {
        url: '#/Service/RemindList',
        key: '#/Service/RemindList',
        title: '事项提醒管理',
        power: '20888.22002.000',
        unClickable: true,
        subBreadcrumb: [{
          url: '#/Service/RemindList/add',
          key: '#/Service/RemindList/add',
          title: '新建事项提醒管理',
          unClickable: true,
        }, {
          url: '#/Service/RemindList/editor',
          key: '#/Service/RemindList/editor',
          title: '编辑事项提醒管理',
          unClickable: true,
        }],
      },
      // {
      //   url: '#/Service/ChangeTeamList',
      //   key: '#/Service/ChangeTeamList',
      //   title: '党支部换届提醒',
      //   power: '20888.22003.000',
      //   unClickable: true,
      //   subBreadcrumb: [{
      //     url: '#/Service/ChangeTeamList/ChangeTeamAdd',
      //     key: '#/Service/ChangeTeamList/ChangeTeamAdd',
      //     title: '新建党支部换届提醒',
      //     unClickable: true,
      //   }]
      // },
    ],
  },
  {
    url: '#/PersonalWork',
    key: '#/PersonalWork',
    defaultImgUrl: require('../styles/images/sidebarMenu/icon_work.png'),
    selectedImgUrl: require('../styles/images/sidebarMenu/icon_work.png'),
    title: '个人工作',
    unClickable: true,
    subMenu: [
      {
        url: '#/PersonalWork/Examine',
        key: '#/PersonalWork/Examine',
        title: '内容审核',
        power: '20008.21802.000',
        subBreadcrumb: [{
          url: '#/PersonalWork/Examine/ArtDetail',
          key: '#/PersonalWork/Examine/ArtDetail',
          title: '内容审核详情',
          unClickable: true,
        },
        {
          url: '#/PersonalWork/Examine/VideoDetail',
          key: '#/PersonalWork/Examine/VideoDetail',
          title: '内容审核详情',
          unClickable: true,
        }],
      },
      {
        url: '#/PersonalWork/MyExport',
        key: '#/PersonalWork/MyExport',
        title: '我的导出',
        power: '20008.21801.000',
      },
    ],
  },
  // 20181030
  {//界面管理
    url: '#/InterfaceManagement',
    title: '界面管理',
    key: '#/InterfaceManagement',
    defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiemianguanli.png'),
    selectedImgUrl: require('../styles/images/sidebarMenu/icon_jiemianguanli.png'),
    subMenu: [
      {
        url: '#/InterfaceManagement/HomeLayout',
        key: '#/InterfaceManagement/HomeLayout',
        title: '首页布局管理',
        defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
        selectedImgUrl: require('../styles/images/sidebarMenu/icon_jianhao.png'),
        unClickable: true,
        subMenu: [{
          url: '#/InterfaceManagement/HomeLayout/Carousel',
          key: '#/InterfaceManagement/HomeLayout/Carousel',
          title: '首页轮播图管理',
          defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
          selectedImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
          power: '20003.21402.000',
          subBreadcrumb: [{
            url: '#/InterfaceManagement/HomeLayout/NewCarousel',
            key: '#/InterfaceManagement/HomeLayout/NewCarousel',
            title: '新建轮播图',
            unClickable: true,
          }, {
            url: '#/InterfaceManagement/HomeLayout/CarouselDetail',
            key: '#/InterfaceManagement/HomeLayout/CarouselDetail',
            title: '轮播图详情',
            unClickable: true,
          }, {
            url: '#/InterfaceManagement/HomeLayout/EditCarousel',
            key: '#/InterfaceManagement/HomeLayout/EditCarousel',
            title: '编辑轮播图',
            unClickable: true,
          }],
        }, {
          url: '#/InterfaceManagement/HomeLayout/Tag',
          key: '#/InterfaceManagement/HomeLayout/Tag',
          title: '首页标签管理',
          defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
          selectedImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
          power: '20003.21401.000',
          subBreadcrumb: [{
            url: '#/InterfaceManagement/HomeLayout/NewTag',
            key: '#/InterfaceManagement/HomeLayout/NewTag',
            title: '新建标签',
            unClickable: true,
          }, {
            url: '#/InterfaceManagement/HomeLayout/EditTag',
            key: '#/InterfaceManagement/HomeLayout/EditTag',
            title: '编辑标签',
            unClickable: true,
          }],
        }, {
          url: '#/InterfaceManagement/HomeLayout/Menu',
          key: '#/InterfaceManagement/HomeLayout/Menu',
          title: '首页菜单管理',
          defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
          selectedImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
          power: '20003.21403.000',
          subBreadcrumb: [{
            url: '#/InterfaceManagement/HomeLayout/NewMenu',
            key: '#/InterfaceManagement/HomeLayout/NewMenu',
            title: '新建菜单',
            unClickable: true,
          }, {
            url: '#/InterfaceManagement/HomeLayout/EditMenu',
            key: '#/InterfaceManagement/HomeLayout/EditMenu',
            title: '编辑菜单',
            unClickable: true,
          }],
        }, {
          url: '#/InterfaceManagement/HomeLayout/ContentManagement',
          key: '#/InterfaceManagement/HomeLayout/ContentManagement',
          title: '首页内容管理',
          power: '20003.21404.000',
        }],
      },
      {
        url: '#/InterfaceManagement/ColumnManagement',
        key: '#/InterfaceManagement/ColumnManagement',
        title: '栏目管理',
        power: '20003.21405.000',
      },
      {
        url: '#/InterfaceManagement/PopularWords',
        key: '#/InterfaceManagement/PopularWords',
        title: '热词管理',
        power: '20003.21406.000',
      },
    ],
  },
  {//企业配置
    url: '#/EnterpriseConfig',
    title: '企业配置',
    key: '#/EnterpriseConfig',
    defaultImgUrl: require('../styles/images/sidebarMenu/icon_qiyepeizhi.png'),
    selectedImgUrl: require('../styles/images/sidebarMenu/icon_qiyepeizhi.png'),
    subMenu: [
      {
        url: '#/EnterpriseConfig/company',
        key: '#/EnterpriseConfig/company',
        title: '企业管理',
        power: '20004.21502.000',
      },
      {
        url: '#/EnterpriseConfig/DepartMent',
        key: '#/EnterpriseConfig/DepartMent',
        title: '企业部门管理',
        power: '20004.21501.000',
      },
      {
        url: '#/EnterpriseConfig/UserManagement',
        key: '#/EnterpriseConfig/UserManagement',
        title: '用户管理',
        power: '20004.21504.000',
        subBreadcrumb: [{
          url: '#/EnterpriseConfig/NewUser',
          key: '#/EnterpriseConfig/NewUser',
          title: '新建用户',
          unClickable: true,
        }, {
          url: '#/EnterpriseConfig/EditUser',
          key: '#/EnterpriseConfig/EditUser',
          title: '编辑用户',
          unClickable: true,
        }, {
          url: '#/EnterpriseConfig/UserManagementDetail',
          key: '#/EnterpriseConfig/UserManagementDetail',
          title: '用户详情',
          unClickable: true,
        }, {
          url: '#/EnterpriseConfig/AuthorizationRang',
          key: '#/EnterpriseConfig/AuthorizationRang',
          title: '数据权限设置',
          unClickable: true,
        }],
      },
      {
        url: '#/EnterpriseConfig/RolePermissions',
        key: '#/EnterpriseConfig/RolePermissions',
        title: '角色权限管理',
        power: '20004.21503.000',
        subBreadcrumb: [{
          url: '#/EnterpriseConfig/AddRolePermissions',
          key: '#/EnterpriseConfig/AddRolePermissions',
          title: '新建角色权限',
          unClickable: true,
        }, {
          url: '#/EnterpriseConfig/EditRolePermissions',
          key: '#/EnterpriseConfig/EditRolePermissions',
          title: '编辑角色权限',
          unClickable: true,
        }, {
          url: '#/EnterpriseConfig/DetailRolePermissions',
          key: '#/EnterpriseConfig/DetailRolePermissions',
          title: '查看角色权限',
          unClickable: true,
        },
        ],
      },
      {
        url: '#/EnterpriseConfig/VirtualGroup',
        key: '#/EnterpriseConfig/VirtualGroup',
        title: '虚拟组管理',
        power: '20004.21505.000',
        subBreadcrumb: [{
          url: '#/EnterpriseConfig/VirtualGroupUser',
          key: '#/EnterpriseConfig/VirtualGroupUser',
          title: '群成员管理',
          unClickable: true,
        }, {
          url: '#/EnterpriseConfig/VirtualGroupAddUser',
          key: '#/EnterpriseConfig/VirtualGroupAddUser',
          title: '添加群成员',
          unClickable: true,
        }],
      },
      {
        url: '#/EnterpriseConfig/Visitor',
        key: '#/EnterpriseConfig/Visitor',
        title: '游客管理',
        power: '20001.21002.000',
      },
    ],
  },
  {//系统设置
    url: '#/SystemSettings',
    title: '系统设置',
    key: '#/SystemSettings',
    defaultImgUrl: require('../styles/images/sidebarMenu/icon_xitong.png'),
    selectedImgUrl: require('../styles/images/sidebarMenu/icon_xitong.png'),
    unClickable: true,
    subMenu: [
      {
        url: '#/SystemSettings/Experience',
        key: '#/SystemSettings/Experience',
        title: '经验值管理',
        power: '20001.21814.000',
        subBreadcrumb: [{
          url: '#/SystemSettings/AddExperience',
          key: '#/SystemSettings/AddExperience',
          title: '经验值添加',
          unClickable: true,
        }, {
          url: '#/SystemSettings/EditExperience',
          key: '#/SystemSettings/EditExperience',
          title: '经验值编辑',
          unClickable: true,
        },
        ],
      },
      {
        url: '#/SystemSettings/ConfigGrade',
        key: '#/SystemSettings/ConfigGrade',
        title: '配置档设定',
        power: '20006.21409.000',
        subBreadcrumb: [{
          url: '#/SystemSettings/AddConfig',
          key: '#/SystemSettings/AddConfig',
          title: '配置档添加',
          unClickable: true,
        }, {
          url: '#/SystemSettings/EditConfig',
          key: '#/SystemSettings/EditConfig',
          title: '配置档编辑',
          unClickable: true,
        },
        ],

      },
      // {
      //   url: '#/SystemSettings/Visitor',
      //   key: '#/SystemSettings/Visitor',
      //   title: '游客管理',
      //   power: '20001.21002.000',
      // }, 
      // {
      //   url: '#/SystemSettings/RolePermissions',
      //   key: '#/SystemSettings/RolePermissions',
      //   title: '角色权限管理',
      //   power: '20001.21301.000',
      //   subBreadcrumb: [{
      //     url: '#/SystemSettings/AddRolePermissions',
      //     key: '#/SystemSettings/AddRolePermissions',
      //     title: '新建角色权限',
      //     unClickable: true,
      //   }, {
      //     url: '#/SystemSettings/EditRolePermissions',
      //     key: '#/SystemSettings/EditRolePermissions',
      //     title: '编辑角色权限',
      //     unClickable: true,
      //   }, {
      //     url: '#/SystemSettings/DetailRolePermissions',
      //     key: '#/SystemSettings/DetailRolePermissions',
      //     title: '查看角色权限',
      //     unClickable: true,
      //   },
      //   ],
      // }, 
      // {
      //   url: '#/SystemSettings/HomeLayout',
      //   key: '#/SystemSettings/HomeLayout',
      //   title: '首页布局管理',
      //   defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
      //   selectedImgUrl: require('../styles/images/sidebarMenu/icon_jianhao.png'),
      //   unClickable: true,
      //   subMenu: [{
      //     url: '#/SystemSettings/HomeLayout/Carousel',
      //     key: '#/SystemSettings/HomeLayout/Carousel',
      //     title: '首页轮播图管理',
      //     defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
      //     selectedImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
      //     power: '20001.21402.000',
      //     subBreadcrumb: [{
      //       url: '#/SystemSettings/HomeLayout/NewCarousel',
      //       key: '#/SystemSettings/HomeLayout/NewCarousel',
      //       title: '新建轮播图',
      //       unClickable: true,
      //     }, {
      //       url: '#/SystemSettings/HomeLayout/CarouselDetail',
      //       key: '#/SystemSettings/HomeLayout/CarouselDetail',
      //       title: '轮播图详情',
      //       unClickable: true,
      //     }, {
      //       url: '#/SystemSettings/HomeLayout/EditCarousel',
      //       key: '#/SystemSettings/HomeLayout/EditCarousel',
      //       title: '编辑轮播图',
      //       unClickable: true,
      //     }],
      //   }, {
      //     url: '#/SystemSettings/HomeLayout/Tag',
      //     key: '#/SystemSettings/HomeLayout/Tag',
      //     title: '首页标签管理',
      //     defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
      //     selectedImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
      //     power: '20001.21401.000',
      //     subBreadcrumb: [{
      //       url: '#/SystemSettings/HomeLayout/NewTag',
      //       key: '#/SystemSettings/HomeLayout/NewTag',
      //       title: '新建标签',
      //       unClickable: true,
      //     }, {
      //       url: '#/SystemSettings/HomeLayout/EditTag',
      //       key: '#/SystemSettings/HomeLayout/EditTag',
      //       title: '编辑标签',
      //       unClickable: true,
      //     }],
      //   }, {
      //     url: '#/SystemSettings/HomeLayout/Menu',
      //     key: '#/SystemSettings/HomeLayout/Menu',
      //     title: '首页菜单管理',
      //     defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
      //     selectedImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
      //     power: '20001.21403.000',
      //     subBreadcrumb: [{
      //       url: '#/SystemSettings/HomeLayout/NewMenu',
      //       key: '#/SystemSettings/HomeLayout/NewMenu',
      //       title: '新建菜单',
      //       unClickable: true,
      //     }, {
      //       url: '#/SystemSettings/HomeLayout/EditMenu',
      //       key: '#/SystemSettings/HomeLayout/EditMenu',
      //       title: '编辑菜单',
      //       unClickable: true,
      //     }],
      //   }, {
      //     url: '#/SystemSettings/HomeLayout/ContentManagement',
      //     key: '#/SystemSettings/HomeLayout/ContentManagement',
      //     title: '首页内容管理',
      //     power: '20001.21404.000',
      //   }],
      // },
      {
        url: '#/SystemSettings/Dictionary',
        key: '#/SystemSettings/Dictionary',
        title: '字典管理',
        defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
        selectedImgUrl: require('../styles/images/sidebarMenu/icon_jianhao.png'),
        unClickable: true,
        subMenu: [
          //   {
          //   url: '#/SystemSettings/Dictionary/Magazines',
          //   key: '#/SystemSettings/Dictionary/Magazines',
          //   title: '杂志系列管理',
          //   power: '20001.21606.000',
          // },
          {
            url: '#/SystemSettings/Dictionary/Apply',
            key: '#/SystemSettings/Dictionary/Apply',
            title: '报名字段管理',
            power: '20001.21502.000',
            subBreadcrumb: [{
              url: '#/SystemSettings/Dictionary/AddApply',
              key: '#/SystemSettings/Dictionary/AddApply',
              title: '新建报名字段',
              unClickable: true,
            }, {
              url: '#/SystemSettings/Dictionary/ApplyDetail',
              key: '#/SystemSettings/Dictionary/ApplyDetail',
              title: '编辑报名字段',
              unClickable: true,
            },
            ],
          },
          // {
          //   url: '#/SystemSettings/Dictionary/TaskTopic',
          //   key: '#/SystemSettings/Dictionary/TaskTopic',
          //   title: '任务主题管理',
          //   subBreadcrumb: [{
          //     url: '#/SystemSettings/Dictionary/TaskTopicAdd',
          //     key: '#/SystemSettings/Dictionary/TaskTopicAdd',
          //     title: '新建任务主题',
          //     unClickable: true,
          //   }, {
          //     url: '#/SystemSettings/Dictionary/TaskTopicEdit',
          //     key: '#/SystemSettings/Dictionary/TaskTopicEdit',
          //     title: '编辑任务主题',
          //     unClickable: true,
          //   },
          //   ],
          // },
          // {
          //   url: '#/SystemSettings/Dictionary/TaskType',
          //   key: '#/SystemSettings/Dictionary/TaskType',
          //   title: '任务类型管理',
          //   subBreadcrumb: [{
          //     url: '#/SystemSettings/Dictionary/TaskTypeAdd',
          //     key: '#/SystemSettings/Dictionary/TaskTypeAdd',
          //     title: '新建类型主题',
          //     unClickable: true,
          //   }, {
          //     url: '#/SystemSettings/Dictionary/TaskTypeEdit',
          //     key: '#/SystemSettings/Dictionary/TaskTypeEdit',
          //     title: '编辑任务类型',
          //     unClickable: true,
          //   },
          //   ],
          // },
        ],
      },
      // {
      //   url: '#/SystemSettings/ColumnManagement',
      //   key: '#/SystemSettings/ColumnManagement',
      //   title: '栏目管理',
      //   power: '20001.21010.000',
      // },
      //  {
      //   url: '#/SystemSettings/PopularWords',
      //   key: '#/SystemSettings/PopularWords',
      //   title: '热词管理',
      //   power: '20001.21011.000',
      // },
      //  {
      //   url: '#/SystemSettings/DepartMent',
      //   key: '#/SystemSettings/DepartMent',
      //   title: '企业部门管理',
      //   power: '20001.21004.000',
      // }, 
      //  {
      //   url: '#/SystemSettings/VirtualGroup',
      //   key: '#/SystemSettings/VirtualGroup',
      //   title: '虚拟群组管理',
      //   power: '20001.21006.000',
      //   subBreadcrumb: [{
      //     url: '#/SystemSettings/VirtualGroupUser',
      //     key: '#/SystemSettings/VirtualGroupUser',
      //     title: '群成员管理',
      //     unClickable: true,
      //   }, {
      //     url: '#/SystemSettings/VirtualGroupAddUser',
      //     key: '#/SystemSettings/VirtualGroupAddUser',
      //     title: '添加群成员',
      //     unClickable: true,
      //   }],
      // },
      {
        url: '#/SystemSettings/versionManagement',
        key: '#/SystemSettings/versionManagement',
        title: '企业版本管理',
        power: '20006.21408.000',
        subBreadcrumb: [{
          url: '#/SystemSettings/AddVersionManagement',
          key: '#/SystemSettings/AddVersionManagement',
          title: '新建版本',
          unClickable: true,
        }, {
          url: '#/SystemSettings/EditVersionManagement',
          key: '#/SystemSettings/EditVersionManagement',
          title: '编辑版本',
          unClickable: true,
        }, {
          url: '#/SystemSettings/DetailVersionManagement',
          key: '#/SystemSettings/DetailVersionManagement',
          title: '查看版本',
          unClickable: true,
        },
        ],
      },
      // {
      //   url: '#/SystemSettings/company',
      //   key: '#/SystemSettings/company',
      //   title: '企业管理',
      //   power: '20001.21012.000',
      // },
      // {
      //   url: '#/SystemSettings/feedBack/Redirect',
      //   key: 'http://t.manage.iyouqu.com.cn/admin/feedback/query.jhtml?youqums',
      //   title: '反馈意见',
      //   power: '20001.21015.000',
      // }, {
      //   url: '#/SystemSettings/reviewReport/Redirect',
      //   key: 'http://t.manage.iyouqu.com.cn/admin/comment/query.jhtml?youqums',
      //   title: '评论举报',
      //   power: '20001.21016.000',
      // }, {
      //   url: '#/SystemSettings/MessageService/Redirect',
      //   key: 'http://t.manage.iyouqu.com.cn/admin/message/query.jhtml?youqums',
      //   title: '消息服务',
      //   power: '20001.21018.000',
      // },
      // {
      //   url: '#/SystemSettings/ServiceAgreement/List',
      //   key: '#/SystemSettings/ServiceAgreement/List',
      //   title: '服务协议',
      //   power: '20001.21811.000',
      // },
      {
        url: '#/SystemSettings/VersionInformation/VersionInformation',
        key: '#/SystemSettings/VersionInformation/VersionInformation',
        title: '应用版本管理',
        power: '20006.21407.000',
        subBreadcrumb: [{
          url: '#/SystemSettings/VersionInformationAdd',
          key: '#/SystemSettings/VersionInformationAdd',
          title: '添加版本信息',
          unClickable: true,
        }, {
          url: '#/SystemSettings/VersionInformationEdit',
          key: '#/SystemSettings/VersionInformationEdit',
          title: '编辑版本信息',
          unClickable: true,
        }, {
          url: '#/SystemSettings/VersionInformationDetail',
          key: '#/SystemSettings/VersionInformationDetail',
          title: '版本信息详情',
          unClickable: true,
        }],
      }, {
        url: '#/SystemSettings/WeightManagement/List',
        key: '#/SystemSettings/WeightManagement/List',
        title: '权重管理',
        power: '20001.21816.000',
      },
      //朱劲松 2019.03.21  屏蔽
      // {
      //   title: '直播设置',
      //   url: '#/SystemSettings/LiveTelecast',
      //   key: '#/SystemSettings/LiveTelecast',
      //   power:'20012.21001.000',//直播权限xwx2018/12/21
      //   subBreadcrumb: [{
      //     url: '#/SystemSettings/LiveTelecast/AddLiveTelecast',
      //     key: '#/SystemSettings/LiveTelecast/AddLiveTelecast',
      //     title: '添加直播间',
      //     unClickable: true,
      //   },{
      //     url: '#/SystemSettings/LiveTelecast/SendSystemMessage',
      //     key: '#/SystemSettings/LiveTelecast/SendSystemMessage',
      //     title: '系统消息列表',
      //     unClickable: true,
      //   },{
      //     url: '#/SystemSettings/LiveTelecast/RoleList',
      //     key: '#/SystemSettings/LiveTelecast/RoleList',
      //     title: '角色列表',
      //     unClickable: true,
      //   },]
      // }
    ],
  },
  {
    url: '#/PartyBuildReport',
    key: '#/PartyBuildReport',
    defaultImgUrl: require('../styles/images/sidebarMenu/icon_dangjianbaobiao.png'),
    selectedImgUrl: require('../styles/images/sidebarMenu/icon_dangjianbaobiao.png'),
    title: '党建报表统计',
    unClickable: true,
    subMenu: [
      {
        url: '#/PartyBuildReport/PartyBuildTask',
        key: '#/PartyBuildReport/PartyBuildTask',
        title: '党建任务统计',
        defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
        selectedImgUrl: require('../styles/images/sidebarMenu/icon_jianhao.png'),
        subMenu: [{
          url: '#/PartyBuildReport/PartyBuildTask/ImportantWorkDeploy',
          key: '#/PartyBuildReport/PartyBuildTask/ImportantWorkDeploy',
          title: '重要工作部署统计',
          power: '20011.25001.000',
          // unClickable: true,
          subBreadcrumb: [{
            url: '#/PartyBuildReport/PartyBuildTask/CompleteRate',
            key: '#/PartyBuildReport/PartyBuildTask/CompleteRate',
            title: '查看完成率',
            unClickable: true,
          }, {
            url: '#/PartyBuildReport/PartyBuildTask/CompleteRateDetail',
            key: '#/PartyBuildReport/PartyBuildTask/CompleteRateDetail',
            title: '查看完成率',
            unClickable: true,
          },
          {
            url: '#/PartyBuildReport/PartyBuildTask/MeetingCompleteRate',
            key: '#/PartyBuildReport/PartyBuildTask/MeetingCompleteRate',
            title: '查看完成率',
            unClickable: true,
          },
          {
            url: '#/PartyBuildReport/PartyBuildTask/SecondCourseDetail',
            key: '#/PartyBuildReport/PartyBuildTask/SecondCourseDetail',
            title: '详情',
            unClickable: true,
          }, {
            url: '#/PartyBuildReport/PartyBuildTask/LastCourseDetail',
            key: '#/PartyBuildReport/PartyBuildTask/LastCourseDetail',
            title: '党支部详情',
            unClickable: true,
          }],
        }, {
          url: '#/PartyBuildReport/PartyBuildTask/MeetingTask',
          key: '#/PartyBuildReport/PartyBuildTask/MeetingTask',
          title: '三会一课任务统计',
          power: '20011.25002.000',
          // unClickable: true,
          subBreadcrumb: [{
            url: '#/PartyBuildReport/PartyBuildTask/ViewCompletionRate',
            key: '#/PartyBuildReport/PartyBuildTask/ViewCompletionRate',
            title: '查看完成率',
            unClickable: true,
          }, {
            url: '#/PartyBuildReport/PartyBuildTask/FirstOrganization',
            key: '#/PartyBuildReport/PartyBuildTask/FirstOrganization',
            title: `详情`,
            unClickable: false,
            subBreadcrumb: [{
              url: '#/PartyBuildReport/PartyBuildTask/PartyBranchesDetail',
              key: '#/PartyBuildReport/PartyBuildTask/PartyBranchesDetail',
              title: '党支部详情',
              unClickable: true,
            }],
          }],
        }],
      },
      {
        url: '#/PartyBuildReport/StudyExamination',
        key: '#/PartyBuildReport/StudyExamination',
        title: '学习考试统计',
        defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
        selectedImgUrl: require('../styles/images/sidebarMenu/icon_jianhao.png'),
        subMenu: [{
          url: '#/PartyBuildReport/StudyExamination/PalmarPartySchool',
          key: '#/PartyBuildReport/StudyExamination/PalmarPartySchool',
          title: '掌上党校统计',
          power: '20011.25003.000',
          // unClickable: true,
          subBreadcrumb: [{
            url: '#/PartyBuildReport/StudyExamination/CompleteRate',
            key: '#/PartyBuildReport/StudyExamination/CompleteRate',
            title: '查看完成率',
            unClickable: true,
          }, {
            url: '#/PartyBuildReport/StudyExamination/SecondCourseDetail',
            key: '#/PartyBuildReport/StudyExamination/SecondCourseDetail',
            title: '详情',
            unClickable: false,
          }, {
            url: '#/PartyBuildReport/StudyExamination/LastCourseDetail',
            key: '#/PartyBuildReport/StudyExamination/LastCourseDetail',
            title: '党支部详情',
            unClickable: true,
          }],
        }, {
          url: '#/PartyBuildReport/StudyExamination/PartyBuildExamination',
          key: '#/PartyBuildReport/StudyExamination/PartyBuildExamination',
          title: '党建考试统计',
          unClickable: false,
          power: '20011.25004.000',
          subBreadcrumb: [{
            url: '#/PartyBuildReport/StudyExamination/ViewCompletionRate',
            key: '#/PartyBuildReport/StudyExamination/ViewCompletionRate',
            title: '查看完成率',
            unClickable: true,
          }, {
            url: '#/PartyBuildReport/StudyExamination/FirstOrganization',
            key: '#/PartyBuildReport/StudyExamination/FirstOrganization',
            title: '详情',
            unClickable: false,
            subBreadcrumb: [{
              url: '#/PartyBuildReport/StudyExamination/PartyBranchesDetail',
              key: '#/PartyBuildReport/StudyExamination/PartyBranchesDetail',
              title: '党支部详情',
              unClickable: true,
            }],
          }],
        }],
      },
      {
        url: '#/PartyBuildReport/PartyAffairsInform',
        key: '#/PartyBuildReport/PartyAffairsInform',
        title: '党务信息统计',
        defaultImgUrl: require('../styles/images/sidebarMenu/icon_jiahao.png'),
        selectedImgUrl: require('../styles/images/sidebarMenu/icon_jianhao.png'),
        subMenu: [{
          url: '#/PartyBuildReport/PartyAffairsInform/PartyFeePay',
          key: '#/PartyBuildReport/PartyAffairsInform/PartyFeePay',
          title: '党费缴纳统计',
          // unClickable: true,
          power: '20011.25005.000',/** 党费缴纳权限码*/
          subBreadcrumb: [
            {
              url: '#/PartyBuildReport/PartyAffairsInform/FirstLevelOrganizationDetails',
              key: '#/PartyBuildReport/PartyAffairsInform/FirstLevelOrganizationDetails',
              title: '详情',
              unClickable: true,
              subBreadcrumb: [{
                url: '#/PartyBuildReport/PartyAffairsInform/PartyBranchesDetails',
                key: '#/PartyBuildReport/PartyAffairsInform/PartyBranchesDetails',
                title: '党支部详情',
                unClickable: true,
              }],
            }],
        }, {
          url: '#/PartyBuildReport/PartyAffairsInform/PartyMemberActivityRate',
          key: '#/PartyBuildReport/PartyAffairsInform/PartyMemberActivityRate',
          title: '党员活跃率统计',
          // unClickable: true,
          power: '20011.25006.000',/** 党员活跃率权限码*/
          subBreadcrumb: [{
            url: '#/PartyBuildReport/PartyAffairsInform/FirstPartyActivityDetail',
            key: '#/PartyBuildReport/PartyAffairsInform/FirstPartyActivityDetail',
            title: '详情',
            unClickable: true,
            subBreadcrumb: [{
              url: '#/PartyBuildReport/PartyAffairsInform/PartyActivityBranchesDetails',
              key: '#/PartyBuildReport/PartyAffairsInform/PartyActivityBranchesDetails',
              title: '党支部详情',
              unClickable: true,
            }],
          }],
        }, {
          url: '#/PartyBuildReport/PartyAffairsInform/PartyMemberHonor',
          key: '#/PartyBuildReport/PartyAffairsInform/PartyMemberHonor',
          title: '党员荣誉值统计',
          // unClickable: false,
          power: '20011.25007.000',
          subBreadcrumb: [{
            url: '#/PartyBuildReport/PartyAffairsInform/FirstOrganization',
            key: '#/PartyBuildReport/PartyAffairsInform/FirstOrganization',
            title: '详情',
            unClickable: false,
            subBreadcrumb: [{
              url: '#/PartyBuildReport/PartyAffairsInform/PartyBranchesDetail',
              key: '#/PartyBuildReport/PartyAffairsInform/PartyBranchesDetail',
              title: '党支部详情',
              unClickable: false,
            }],
          }],
        },
        ],
      },
    ],
  },
  {
    url: '#/OperativeReport',
    key: '#/OperativeReport',
    defaultImgUrl: require('../styles/images/sidebarMenu/icon_yunyingbaobiao.png'),
    selectedImgUrl: require('../styles/images/sidebarMenu/icon_yunyingbaobiao.png'),
    title: '运营报表统计',
    unClickable: true,
    subMenu: [
      {
        url: '#/OperativeReport/RoundupCollect',
        key: '#/OperativeReport/RoundupCollect',
        title: '摘要汇总表',
        power: '20009.21906.000',
      }, {
        url: '#/OperativeReport/UserActionData',
        key: '#/OperativeReport/UserActionData',
        title: '用户行为数据',
        power: '20009.21907.000',
        subBreadcrumb: [{
          url: '#/OperativeReport/UserActionData/Detail',
          key: '#/OperativeReport/UserActionData/Detail',
          title: '详情',
          unClickable: true,
        }],
      }, {
        url: '#/OperativeReport/DepartmentActionData',
        key: '#/OperativeReport/DepartmentActionData',
        title: '部门行为数据',
        power: '20009.21901.000',
      }, {
        url: '#/OperativeReport/PartyActionData',
        key: '#/OperativeReport/PartyActionData',
        title: '党员行为数据',
        power: '20009.21903.000',
        subBreadcrumb: [{
          url: '#/OperativeReport/PartyActionData/Detail',
          key: '#/OperativeReport/PartyActionData/Detail',
          title: '详情',
          unClickable: true,
        }],
      }, {
        url: '#/OperativeReport/PointsStatistics',
        key: '#/OperativeReport/PointsStatistics',
        title: '积分统计',
        power: '20009.21904.000',
      }, {
        url: '#/OperativeReport/ExperienceStatistics',
        key: '#/OperativeReport/ExperienceStatistics',
        title: '经验统计',
        power: '20009.21902.000',
      }, {
        url: '#/OperativeReport/UserClick',
        key: '#/OperativeReport/UserClick',
        title: '用户点击行为统计',
        power: '20009.21908.000',
      }, {
        url: '#/OperativeReport/UserSigned',
        key: '#/OperativeReport/UserSigned',
        title: '用户签到统计',
        power: '20009.21905.000',
      },
    ],
  },

];

//declaration
